; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "NmapSI4"
!define PRODUCT_VERSION "svn06082008-rev364"
!define PRODUCT_PUBLISHER "NmapSI4"
!define PRODUCT_WEB_SITE "http://nmapsi4.netsons.org"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\nmapsi4-logr.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
!define MUI_UNICON "${NSISDIR}\Contrib\Graphics\Icons\modern-uninstall.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_CHECKBOX
!insertmacro MUI_PAGE_LICENSE "..\nmapsi4-svn\README.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "NmapSI4"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES

; ### Attivare solo in stand-alone ###
; Finish page 
;!define MUI_FINISHPAGE_RUN "$INSTDIR\nmapsi4.exe"
;!define MUI_FINISHPAGE_SHOWREADME "$INSTDIR\README.txt"
;!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "..\pack\NmapSI4-svn.exe"
InstallDir "$PROGRAMFILES\NmapSI4"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "Core" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "..\nmapsi4-svn\README.txt"
  File "..\nmapsi4-svn\QtGui4.dll"
  File "..\nmapsi4-svn\QtCore4.dll"
  File "..\nmapsi4-svn\nmapsi4-logr.exe"
  File "..\nmapsi4-svn\nmapsi4.exe"
  File "..\nmapsi4-svn\mingwm10.dll"
  File "..\nmapsi4-svn\COPYING.txt"
  File "..\nmapsi4-svn\AUTHORS.txt"
  File "..\nmapsi4-svn\TODO.txt"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS\$ICONS_GROUP"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\NmapSI4.lnk" "$INSTDIR\nmapsi4.exe"
  CreateShortCut "$DESKTOP\NmapSI4.lnk" "$INSTDIR\nmapsi4.exe"
  CreateShortCut "$QUICKLAUNCH.lnk" "$INSTDIR\nmapsi4.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Language" SEC02
  SetOverwrite on
  File "..\nmapsi4-svn\Language\nmapsi4-logr_de.qm"
  File "..\nmapsi4-svn\Language\nmapsi4-logr_es.qm"
  File "..\nmapsi4-svn\Language\nmapsi4-logr_fr.qm"
  File "..\nmapsi4-svn\Language\nmapsi4-logr_it.qm"
  File "..\nmapsi4-svn\Language\nmapsi4-logr_pl.qm"
  File "..\nmapsi4-svn\Language\nmapsi4_de.qm"
  File "..\nmapsi4-svn\Language\nmapsi4_es.qm"
  File "..\nmapsi4-svn\Language\nmapsi4_fr.qm"
  File "..\nmapsi4-svn\Language\nmapsi4_it.qm"
  File "..\nmapsi4-svn\Language\nmapsi4_pl.qm"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -AdditionalIcons
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk" "$INSTDIR\uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\nmapsi4-logr.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\nmapsi4-logr.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} ""
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) è stato rimosso dal tuo computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Sei sicuro di voler rimuovere $(^Name) e tutti i suoi componenti?" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\nmapsi4_pl.qm"
  Delete "$INSTDIR\nmapsi4_it.qm"
  Delete "$INSTDIR\nmapsi4_fr.qm"
  Delete "$INSTDIR\nmapsi4_es.qm"
  Delete "$INSTDIR\nmapsi4_de.qm"
  Delete "$INSTDIR\nmapsi4-logr_pl.qm"
  Delete "$INSTDIR\nmapsi4-logr_it.qm"
  Delete "$INSTDIR\nmapsi4-logr_fr.qm"
  Delete "$INSTDIR\nmapsi4-logr_es.qm"
  Delete "$INSTDIR\nmapsi4-logr_de.qm"
  Delete "$INSTDIR\TODO.txt"
  Delete "$INSTDIR\AUTHORS.txt"
  Delete "$INSTDIR\COPYING.txt"
  Delete "$INSTDIR\mingwm10.dll"
  Delete "$INSTDIR\nmapsi4.exe"
  Delete "$INSTDIR\nmapsi4-logr.exe"
  Delete "$INSTDIR\QtCore4.dll"
  Delete "$INSTDIR\QtGui4.dll"
  Delete "$INSTDIR\README.txt"

  Delete "$SMPROGRAMS\$ICONS_GROUP\Uninstall.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\Website.lnk"
  Delete "$QUICKLAUNCH.lnk"
  Delete "$DESKTOP\NmapSI4.lnk"
  Delete "$SMPROGRAMS\$ICONS_GROUP\NmapSI4.lnk"

  RMDir "$SMPROGRAMS\$ICONS_GROUP"
  RMDir "$INSTDIR"
  RMDir ""

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd